### ISSUE TITLE
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 14; The prefix "ns5" for element "ns5:Type" is not bound.

### ISSUE THREAD

**Issue by javaHelper** [javadev/underscore-java#233]
I am getting below error - 

```
Exception in thread "main" java.lang.IllegalArgumentException: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 14; The prefix "ns5" for element "ns5:Type" is not bound.
	at com.github.underscore.lodash.Xml.fromXml(Xml.java:1322)
	at com.github.underscore.lodash.Xml.fromXml(Xml.java:1293)
	at com.github.underscore.lodash.U.fromXml(U.java:1995)
	at com.example.MyDemo.main(MyDemo.java:16)
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 14; The prefix "ns5" for element "ns5:Type" is not bound.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:284)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at com.github.underscore.lodash.Xml$Document.createDocument(Xml.java:1402)
	at com.github.underscore.lodash.Xml$Document.access$400(Xml.java:1388)
	at com.github.underscore.lodash.Xml.fromXml(Xml.java:1306)
	... 3 more

```

Code
```
String response = "<FinalResponse>\r\n" + 
				"   <ns5:Type>SUCCESS</ns5:Type>\r\n" + 
				"   <ns5:Code>0</ns5:Code>\r\n" + 
				"</FinalResponse>";
		
		Map<String, Object> map = (Map<String, Object>) U.fromXml(response);
		
	    String json = "[{\"id\":\"1\",\"name\":\"Bratislava\",\"population\":\"432000\"},{\"id\":\"2\",\"name\":\"Budapest\",\"population\":\"1759000\"},{\"id\":\"3\",\"name\":\"Prague\",\"population\":\"1280000\"},{\"id\":\"4\",\"name\":\"Warsaw\",\"population\":\"1748000\"},{\"id\":\"5\",\"name\":\"Los Angeles\",\"population\":\"3971000\"},{\"id\":\"6\",\"name\":\"New York\",\"population\":\"8550000\"},{\"id\":\"7\",\"name\":\"Edinburgh\",\"population\":\"464000\"},{\"id\":\"8\",\"name\":\"Berlin\",\"population\":\"3671000\"}]";
	    List<Object> list = (List<Object>) U.fromJson(json);
	    U.set(map, "soapenv:Envelope.soapenv:Body.getMyData.Visit.item", list);
	    System.out.println(U.toXml(map));
```

**Comment by javadev** [comment]
This code works for me:

```java
        String response = "<FinalResponse xmlns:ns5=\"urn:mybay.com:enterprise:schemas:common:elements\">\r\n" + 
				"   <ns5:Type>SUCCESS</ns5:Type>\r\n" + 
				"   <ns5:Code>0</ns5:Code>\r\n" + 
				"</FinalResponse>";
		
		Map<String, Object> map = (Map<String, Object>) U.fromXml(response);
```

**Comment by javadev** [comment]
Or this code:

```java
        String response = "<FinalResponse>\r\n" + 
				"   <Type>SUCCESS</Type>\r\n" + 
				"   <Code>0</Code>\r\n" + 
				"</FinalResponse>";
		
		Map<String, Object> map = (Map<String, Object>) U.fromXml(response);
```

**Comment by javaHelper** [comment]
Ok got it. In order to support, ns5, ns7 etc, we need to add xmlns immediately above the xml root tag.
