### ISSUE TITLE
java.util.regex.PatternSyntaxException

### ISSUE THREAD

**Issue by timawesomeness** [javadev/underscore-java#238]
```
java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 14
    \{\s*(\d*)\s*}
                  ^
        at java.util.regex.Pattern.compileImpl(Native Method)
        at java.util.regex.Pattern.compile(Pattern.java:1340)
        at java.util.regex.Pattern.<init>(Pattern.java:1324)
        at java.util.regex.Pattern.compile(Pattern.java:946)
        at com.github.underscore.U.<clinit>(U.java:51)
```

https://github.com/javadev/underscore-java/commit/e7504ba4644d1cb795b1f25c09c7a637535b4d32#diff-2bab2dc5b627b10f541b9cd9dc9c4504R51

Probably only occurs on Android

**Comment by javadev** [comment]
Thank you for the issue. It will be fixed soon.

**Comment by javadev** [comment]
The new version was released today. 🎉
