### ISSUE TITLE
JSON to XML conversion heap optimization

### ISSUE THREAD

**Issue by yuri1969** [javadev/underscore-java#597]
Using *underscore* 1.99 on x86-64 Java 17 with the default GC settings, it seems the heap consumption gets out of hand quickly on large(ish) JSON files.

It is possible to convert a ~180MB JSON (the structure is basically a large array of 90000+ objects) to XML using a rather old [org.json](https://mvnrepository.com/artifact/org.json/json)-based utility with `-Xmx4g`. Converting the same file to XML requires `-Xmx7g` using *underscore*.

It seems there might be a potential for optimizing heap allocation of the JSON to XML conversion, right?

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
        at java.base/java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:228)
        at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:582)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:179)
        at com.github.underscore.Xml$XmlStringBuilder.newLine(Xml.java:149)
        at com.github.underscore.Xml$XmlObject.addToBuilder(Xml.java:567)
        at com.github.underscore.Xml$XmlObject.writeXml(Xml.java:531)
        at com.github.underscore.Xml$XmlValue.writeXml(Xml.java:793)
        at com.github.underscore.Xml$XmlObject.addElement(Xml.java:687)
        at com.github.underscore.Xml$XmlObject.processElements(Xml.java:616)
        at com.github.underscore.Xml$XmlObject.writeXml(Xml.java:517)
        at com.github.underscore.Xml$XmlValue.writeXml(Xml.java:793)
        at com.github.underscore.Xml$XmlObject.addElement(Xml.java:687)
        at com.github.underscore.Xml$XmlObject.processElements(Xml.java:616)
        at com.github.underscore.Xml$XmlObject.writeXml(Xml.java:517)
        at com.github.underscore.Xml$XmlValue.writeXml(Xml.java:793)
        at com.github.underscore.Xml$XmlObject.addElement(Xml.java:687)
        at com.github.underscore.Xml$XmlObject.processElements(Xml.java:616)
        at com.github.underscore.Xml$XmlObject.writeXml(Xml.java:517)
        at com.github.underscore.Xml.checkLocalMap(Xml.java:1196)
        at com.github.underscore.Xml.toXml(Xml.java:1159)
        at com.github.underscore.Xml.toXml(Xml.java:1130)
        at com.github.underscore.U.jsonToXml(U.java:2638)
        at com.github.underscore.U.jsonToXml(U.java:2672)
        at com.test.Converter.jsonToXml(Converter.java:26)
        at com.test.Converter.main(Converter.java:16)
```

**Comment by javadev** [comment]
I've devised a solution that could be beneficial

https://github.com/javadev/underscore-java/pull/598

**Comment by javadev** [comment]
The option JsonToXmlMode.REMOVE_ATTRIBUTES is available for U.jsonToXml(json). It decreases the size of the generated XML file.

The Java 17 version might lead to an increased library load from https://github.com/javadev/underscore-java17.

**Comment by javadev** [comment]
The investigation into the reduction of used memory is currently underway.
